#! /bin/bash

if [ -z $1 ]
then
  t=10
else
  t=$1
fi

if [ -z "$2" ]
then
  n="lastpicture.jpeg"
else
  n=$2
fi

while :; do
  imagesnap -w 1.0 $n
  bash ./sendpic
  # imagesnap -w 1.0 test_images/$(date +%y%m%d%H%M%S).jpg
  # say "Picture taken"
  sleep $t
done
